# fly.toml app configuration file generated for habitual-trends-akdc9g on 2026-01-26T09:30:32Z
# fly.toml app configuration file generated for habitual-trends-akdc9g on 2026-01-26T10:09:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'habitual-trends-akdc9g'
<<<<<<< HEAD
primary_region = 'ams'
=======
primary_region = 'jnb'
>>>>>>> e62bd8ecca84d86e5c3958f2a32fa3ae4e2f198e

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
<<<<<<< HEAD
  memory_mb = 256

=======
  memory_mb = 1024
>>>>>>> e62bd8ecca84d86e5c3958f2a32fa3ae4e2f198e
